% gen_template.m
% Writes source/correlator/template_pkg.sv with the m-sequence correlator templates.
% Run from the octave directory:  octave --no-gui -q gen_template.m
%
% Bit ordering: TEMPLATE_N[i] = seq(i+1), so bit 0 is the first chip transmitted.
% Each template is zero-extended to MAX_TAPS bits; slice [N-1:0] to use it.

degrees  = [7 10 12];          % 127, 1023, 4095 taps
max_taps = 4095;
outfile  = "../source/correlator/template_pkg.sv";

fid = fopen(outfile, "w");
fprintf(fid, "// template_pkg.sv\n");
fprintf(fid, "// GENERATED by octave/gen_template.m -- do not edit.\n");
fprintf(fid, "// TEMPLATE_N[i] = m_sequence(deg)(i+1); bit value 0 = +1, 1 = -1.\n\n");
fprintf(fid, "package template_pkg;\n\n");
fprintf(fid, "    localparam int MAX_TAPS = %d;\n\n", max_taps);

for deg = degrees
    seq = m_sequence(deg);
    n   = numel(seq);
    bits = fliplr(seq);                         % MSB (bit n-1) first
    fprintf(fid, "    // degree %d m-sequence, %d taps\n", deg, n);
    fprintf(fid, "    localparam logic [MAX_TAPS-1:0] TEMPLATE_%d = %d'({\n", n, max_taps);
    nchunk = ceil(n / 64);
    first  = n - 64 * (nchunk - 1);             % MSB chunk takes the remainder
    k = 1;
    for c = 1:nchunk
        w = 64;
        if c == 1
            w = first;
        endif
        fprintf(fid, "        %d'b%s", w, sprintf("%d", bits(k:k+w-1)));
        k = k + w;
        if c < nchunk
            fprintf(fid, ",\n");
        else
            fprintf(fid, "\n");
        endif
    endfor
    fprintf(fid, "    });\n\n");
endfor

fprintf(fid, "endpackage\n");
fclose(fid);
printf("wrote %s\n", outfile);

